apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
    
  project: default
  source:
    repoURL: https://github.com/Doctor2kUa/testrepo.git
    targetRevision: HEAD
    path: /

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      