name: Sync from preprod
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync-to-preprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: Doctor2kUa/testrepo
          path: sourcerepo
      - shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          sh; rsync -av sourcerepo/ . --exclude sourcerepo --exclude .git --exclude .gitignore --exclude .github
          sh; rm -rf sourcerepo
          git add . 
          sh; ls -la 
          
          git commit -m "Updated ${{ github.event.repository.updated_at}} "
          git push
