name: Example
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: Doctor2kUa/testrepo
          path: source
      - shell: bash
        run: |
          date > 1.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add 1.txt
          sh; ls -la
          sh; ls -la source
          git commit -m updated
          git push
