name: Example
on:
  push:
    branches:
      - "main"
permissions:
  contents: write
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main
          repository: Doctor2kUa/testrepo
          
      - name: check1
        run: |
          ls -la 
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          date > 1.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add 1.txt
          sh; ls -la
          git commit -m updated
          git push
