env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
name: Build and Deploy




on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'yamls/**'
      - 'yamls/**/**'

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'write'
      id-token: 'write'
      packages: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: tolower
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ env.IMAGE_NAME }}
      - id: step2
        run: echo ${{ steps.tolower.outputs.lowercase }}
